
format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$line_break\
$jobs\
$battery\
$character"""

right_format = '$status$cmd_duration'

[battery]
format = '[$percentage]($style) '

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[cmd_duration]
format = ' took [$duration]($style)'

[time]
format = '$time '
disabled = false

[status]
format = ' [$symbol $status]($style)'
map_symbol = true
disabled = false

